[shell]
program = ".nix-profile/bin/zellij"

[env]
LD_LIBRARY_PATH = ""

[window]
option_as_alt = "Both"

[window.dimensions]
columns = 120
lines = 40

[window.padding]
x = 1
y = 1

[font]
size = 14
normal = { family = "Iosevka Term", style = "Light" }
bold = { style = "Medium" }
bold_italic = { style = "Medium Italic" }
italic = { style = "Light Italic" }
