if [[ -d /usr/local/share/zsh/site-functions ]]; then
  fpath=(/usr/local/share/zsh/site-functions $fpath)
fi

source ${ZDOTDIR:-$HOME}/.zprezto/runcoms/zlogin

[[ -e ~/.ssh/*.pem ]] && ssh-add ~/.ssh/*.pem 2>/dev/null

export GPG_TTY=$(tty)
[[ -f ~/.gpg-agent-info ]] && source ~/.gpg-agent-info
if [[ -S "${GPG_AGENT_INFO%%:*}" ]]; then
  export GPG_AGENT_INFO
else
  eval $(gpg-agent --daemon --write-env-file ~/.gpg-agent-info)
fi

if [[ -e ~/.zlogin.local ]]; then
  source ~/.zlogin.local
fi
