#!/usr/bin/env zsh
#
if [[ -d /usr/local/opt/zplug ]]; then
  export ZPLUG_HOME=/usr/local/opt/zplug
  source $ZPLUG_HOME/init.zsh

  zplug "zsh-users/zsh-autosuggestions"
  zplug "zsh-users/zsh-syntax-highlighting"

  zplug check || zplug install
fi
