path=(
    ~/bin/unix
    ~/.local/bin
    ~/.rvm/bin
    ./node_modules/.bin
    $path
)

if [[ "$OSTYPE" == darwin* ]]; then
    export BROWSER='open'
    path=(
        ~/bin/mac
        ~/Library/Haskell/bin
        $path
    )
fi

export EDITOR='nvim'
export VISUAL='nvim'
export PAGER='less'

export GRADLE_OPTS="$GRADLE_OPTS -Dorg.gradle.daemon=true"

if [[ -e ~/.zshenv.local ]]; then
    source ~/.zshenv.local
fi
