#!/usr/bin/env ruby

require 'pathname'

LINKS = %w{
  ghc/ghci.conf
  gitconfig
  gitignore
  i3
  nvim
  nvimrc
  racketrc
  tmux
  tmux.conf
  vimrc
  zlogin
  zlogout
  zprezto
  zpreztorc
  zprofile
  zshenv
  zshrc
}

@dir = Pathname.new(File.dirname(__FILE__)).realpath
@dotfiles = @dir + 'dotfiles'
@home = Pathname.new(ENV['HOME']).realpath

def run command
  unless system command
    $stderr.puts "FAIL: #{command}"
    exit 1
  end
end

def link source, destination
  destination.dirname.mkpath()
  destination.unlink() if destination.symlink?
  File.symlink source, destination
end

puts 'Symlinking configuration files'
LINKS.each do |file|
  link (@dotfiles + file), (@home + ".#{file}")
end

unless (@dir + 'first-time-run').exist?
  puts 'Running first-time setup'
  run (@dir + 'first-time.sh').to_s
  (@dir + 'first-time-run').open 'w' do |f|
    f.write ''
  end
end

puts 'Installing vim plugins'
unless (@home + '.vim/bundle/vundle').exist?
  run 'git clone https://github.com/gmarik/vundle.git ~/.vim/bundle/vundle'
end

run 'vim +BundleInstall +BundleUpdate +qall'
run 'vim +VimProcInstall +qall'
run (@home + '.vim/bundle/YouCompleteMe/install.py').to_s
