#!/usr/bin/env ruby

puts "Symlinking configuration files"
cwd = File.expand_path File.dirname __FILE__
exclude = ["#{cwd}/init", "#{cwd}/README.md"]
home = ENV['HOME']
(Dir["#{cwd}/*"] - exclude).each do |dotfile|
  name = File.basename dotfile
  `ln -sf "#{dotfile}" "#{home}/.#{name}"`
end

puts "Installing vim plugins"
if File.exist? "#{home}/.vim/bundle/vundle"
  `cd ~/.vim/bundle/vundle && git pull`
else
  `git clone https://github.com/gmarik/vundle.git ~/.vim/bundle/vundle`
end
`vim +BundleInstall +qall`

Dir["#{home}/.vim/bundle/*"].each do |vim_plugin_dir|
  puts "Upgrading #{File.basename(vim_plugin_dir)}"
  `cd #{vim_plugin_dir} && git pull`
end
