#!/bin/bash

ln -s "$(cd $(dirname $BASH_SOURCE) && pwd)/vimrc" ~/.vimrc
[[ ! -e ~/.vim/bundle/vundle ]] && git clone https://github.com/gmarik/vundle.git ~/.vim/bundle/vundle
vim +BundleInstall +qall
