#!/usr/bin/env ruby

require 'fileutils'
require 'yaml'

bundles_dir = File.join ENV['HOME'], '.vim', 'bundle'
bundles = YAML::load File.open('bundles.yml')

FileUtils.cd bundles_dir

def synchronize (create_command, update_command, name, options)
  url = options['url']
  unless Dir.exists? name
    puts "  Unpacking #{url} into #{name}"
    `#{create_command} #{url} #{name}`
    return
  end

  puts "  Updating #{name}"
  `(cd #{name} && #{update_command})`
end

synchronizers = {
  'git' => lambda do |name, options|
    synchronize 'git clone', 'git pull', name, options
  end,
  'hg' => lambda do |name, options|
    synchronize 'hg clone', 'hg pull', name, options
  end,
  '' => lambda do |name, options|
    vcs = options['vcs']
    next STDERR.puts "  No VCS specified for #{name}" if not vcs or vcs == ''
    next STDERR.puts "  #{name} has an unknown VCS: #{vcs}"
  end
}

bundles.each do |name, options|
  vcs = options['vcs']
  vcs = '' unless synchronizers.has_key? vcs
  synchronizers[vcs].call name, options
end

removed_bundles = Dir.glob('*').reject { |dir| bundles.find { |name, options| name == dir } }
removed_bundles.each do |dir|
  puts "  Removing #{dir}"
  FileUtils.rm_rf dir
end
