#!/usr/bin/env ruby

require 'fileutils'
require 'yaml'

bundles_dir = File.join ENV['HOME'], '.vim', 'bundle'
git_bundles = YAML::load File.open('git-bundles.yml')

FileUtils.cd bundles_dir

git_bundles.each do |name, options|
  url = options['url']
  unless Dir.exists? name
    puts "  Unpacking #{url} into #{name}"
    `git clone #{url} #{name}`
    next
  end

  puts "  Updating #{name}"
  `(cd #{name} && git pull)`
end

removed_bundles = Dir.glob('*').reject { |dir| git_bundles.find { |name, options| name == dir } }
removed_bundles.each do |dir|
  puts "  Removing #{dir}"
  FileUtils.rm_rf dir
end
