#!/usr/bin/env zsh

if [[ $(git name) == 'master' ]]; then
    echo >&2 'Do not work on the master branch.'
    exit 1
fi

git first-push

url=$(git config --get remote.origin.url)
repo=$(gsed -r 's/^git@github.com:|\.git$//g' <<< $url)

open "https://github.com/$repo/compare/$(git name)?expand=1"
