#!/usr/bin/env ruby

branch = `git name`.strip
if branch == 'master'
    $stderr.puts 'Do not work on the master branch.'
    exit 1
end

system('git', 'first-push')

url = `git config --get remote.origin.url`.strip
repo = url.gsub(/^git@github.com:|\.git$/, '')
system('open', "https://github.com/#{repo}/compare/#{branch}?expand=1")
