templates:
  params:
    author-name: Samir Talwar
    author-email: samir@noodlesandwich.com
    copyright: Samir Talwar
    github-username: SamirTalwar

ghc-options:
  $everything: -pgma clang -pgmc clang

nix:
  enable: true
