templates:
  params:
    author-name: Samir Talwar
    author-email: samir@noodlesandwich.com
    copyright: Samir Talwar
    github-username: SamirTalwar

extra-include-dirs:
  - /usr/local/opt/openssl/include
extra-lib-dirs:
  - /usr/local/opt/openssl/lib
