#!/usr/bin/env zsh

[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm"

set -e

function exists {
    (( $+commands[$1] ))
}

function if-exists {
    if exists $1; then
        "$@"
    fi
}

function update-gems {
    gem update --system && gem update && gem cleanup
}

if exists brew; then
    brew update
    brew upgrade --all
    brew cleanup
    brew cask cleanup
    brew linkapps
fi

if exists apt-get; then
    apt-get update
    apt-get upgrade
fi

if exists rvm; then
    rvm get head
    rvm cleanup all
    rvm reload
fi

if exists gem; then
    if exists rvm; then
        (rvm use ruby@global && update-gems)
    fi

    update-gems
fi

if exists pip; then
    pip install --upgrade setuptools
    pip install --upgrade pip
fi

if exists npm; then
    npm update -g
    npm upgrade -g
fi

if-exists cabal update

if exists docker && (! exists boot2docker || [[ $(boot2docker status) == 'running' ]]); then
    docker images | awk '$2 == "latest" { print $1 }' | grep -v _ | xargs -n1 docker pull
    docker-cleanup
fi
