#!/usr/bin/env zsh

wait_length=0
while not "$@"; do
    sleep 1
    wait_length=$((wait_length + 1))
    if [[ $(($wait_length % 10)) -eq 0 ]]; then
        echo "Waited for $wait_length seconds..." >&2
    fi
done
