#!/usr/bin/env bash

set -e
set -u

export DESKTOP_SESSION=sway
export GDMSESSION=sway
export XDG_CURRENT_DESKTOP=sway
export XDG_SESSION_DESKTOP=sway

export MOZ_ENABLE_WAYLAND=1
export MOZ_DBUS_REMOTE=1

# shellcheck disable=SC2046
export $(gnome-keyring-daemon --start)

exec sway
